#!/usr/bin/env python3
from ev3dev2.motor import LargeMotor, OUTPUT_A, OUTPUT_B, OUTPUT_C, SpeedPercent, MoveTank
from ev3dev2.sensor import INPUT_1, INPUT_4
from ev3dev2.sensor.lego import InfraredSensor, TouchSensor
from ev3dev2.led import Leds
from time import *
ir = InfraredSensor() 
ir.mode = 'IR-PROX'
drive = MoveTank(OUTPUT_B,OUTPUT_C)
while True:
    dist = int(ir.value())
    sleep(1)
    if dist < 20:
        drive.on_for_rotations(SpeedPercent(70), SpeedPercent(70), 5)
    elif 20 < dist and dist < 62:
        drive.on_for_rotations(SpeedPercent(-30), SpeedPercent(-70), 1)
    elif dist > 62:
        drive.on_for_rotations(SpeedPercent(-70), SpeedPercent(-70), 1) 
